apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
      annotations:
        argocd-image-updater.argoproj.io/image-list: mysite=harryjdh/mysite
        argocd-image-updater.argoproj.io/mysite.update-strategy: latest
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: deployment
    spec:
      containers:
        - name: mysite
          image: harryjdh/mysite:23
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-database

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password

            - name: MYSQL_HOST
              value: "mysql"   # service 이름

            - name: MYSQL_PORT
              value: "3306"

