apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysite-ingress
spec:
  rules:
  - host: mysite.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysite-svc
            port:
              number: 8000

      - path: /static
        pathType: Prefix
        backend:
          service:
            name: mysite-svc
            port:
              number: 8000

